# Generated by Django 4.0.6 on 2022-08-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_workexperience_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
