# Generated by Django 4.0.6 on 2022-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_project_id_alter_workexperience_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
